
project_id = "svfmlcaoarrqvgzriwov"

[functions.update_user_profile]
body = """
CREATE OR REPLACE FUNCTION update_user_profile(
  user_id UUID,
  full_name_param TEXT,
  email_param TEXT,
  company_param TEXT
) RETURNS VOID AS $$
BEGIN
  UPDATE public.profiles
  SET 
    full_name = full_name_param,
    email = email_param,
    company = company_param,
    updated_at = now()
  WHERE id = user_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
"""

[functions.get_user_profile_by_id]
body = """
CREATE OR REPLACE FUNCTION get_user_profile_by_id(lookup_id UUID)
RETURNS TABLE (
  id UUID,
  full_name TEXT,
  email TEXT,
  company TEXT
) AS $$
BEGIN
  RETURN QUERY
  SELECT p.id, p.full_name, p.email, p.company
  FROM public.profiles p
  WHERE p.id = lookup_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
"""
