// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://svfmlcaoarrqvgzriwov.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN2Zm1sY2FvYXJycXZnenJpd292Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3MjI1ODAsImV4cCI6MjA2MDI5ODU4MH0.2LHRvttS5Dtp5ErHvQIP8rQF1GGh9BlvokzTZvLBHtY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);