name: Deploy to DEV

on:
  push:
    branches:
      - 'develop'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install Bun and add to PATH
      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      # Step 3: Cache Bun Dependencies
      - name: Cache Bun Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.bun
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      # Step 4: Install dependencies and build
      - name: Install dependencies
        run: bun install --frozen-lockfile --verbose

      - name: Build the project
        run: bun run build:dev

      # Step 5: Authenticate to Google Cloud
      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_DEV_SERVICE_ACCOUNT_KEY }}'

      # Step 6: Deploy to Cloud Storage DEV Bucket
      - name: Deploy to Cloud Storage DEV Bucket
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_DEV_SERVICE_ACCOUNT_KEY }}
          CLOUD_BUCKET_NAME: ${{ secrets.GCP_DEV_BUCKET_NAME }}
        run: |
          gsutil -m rsync -r ./dist gs://$CLOUD_BUCKET_NAME