name: Deploy to DEV

on:
  push:
    branches:
      - 'develop'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install Bun and add to PATH
      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - name: Verify Bun installation
        run: bun --version

      # Step 3: Install dependencies and build
      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build the project
        run: bun run build:dev

      # Step 4: Authenticate to Google Cloud
      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_DEV_SERVICE_ACCOUNT_KEY }}'

      # Step 5: Deploy to Cloud Storage DEV Bucket
      - name: Deploy to Cloud Storage DEV Bucket
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_DEV_SERVICE_ACCOUNT_KEY }}
        run: |
          gcloud auth activate-service-account --key-file="${{ secrets.GCP_DEV_SERVICE_ACCOUNT_KEY }}"
          gsutil -m rsync -r ./dist gs://meuchapa-dev-frontend